theme: jekyll-theme-cayman
title: C+++ IDE
description: A lightweight and modern C++ IDE on macOS Platform
show_downloads: true
github:
    zip_url: https://github.com/23786/Cppp-IDE/releases/download/v2.1.0/C+++_2_1_0.dmg.zip
